blank_issues_enabled: true
contact_links:
  - name: Something else?
    url: https://github.com/solusapp/solus/discussions
    about: Feel free to ask and answer questions over in GitHub Discussions
  - name: solus Community Support
    url: solus.tech
    about: solus Community - a place to ask, learn and engage with others
